### ISSUE TITLE
Not sure how to make it work with LSPatch

### ISSUE THREAD

**Issue by princawa** [xHookman/IGexperiments#11]
Hello, 

I've been trying to make your app work with LSPatch, but I'm unsure how. You did mention that it is supported on your Github, but I'm not exactly sure what I'm doing wrong.

[Here are the steps I'm taking when trying to enable the app with LSPatch](https://photos.google.com/share/AF1QipMSrCIfNcOTQ2FO1Z6cHJnQhaVl3dkKraiWknK2dU_J3ViQ3KnleJnUefhuzgXJNQ/photo/AF1QipO0IRLwJXRV9tcBgWeLVwrbCAnwJG4RwG3t2X72?key=Q0ppU0QxVmJmZzVLbHFDZzlUcVF4R29sZnhFdnhn). Maybe you can help me out and let me know if I'm doing anything incorrectly. I would really appreciate it :)

Best,
Facundo Holzmeister

**Comment by ReSo7200** [comment]
Hey!

You are doing two wrong things.

First, once you patched Instagram with the module.

You have to patch the module with the module it self.(IGEXPERIMENTS embed module -> IGEXPERIMENTS)

Second, you have to go into the IGEXPERIMENTS app, and click the kill instagram button(red text)

**Comment by ReSo7200** [comment]
Please tell me if it gave u root not granted.

**Comment by princawa** [comment]
Hey!

First off, I just want to thank you for your response and help! I really do appreciate it.

[So I did your extra steps (Patching the module with itself & killing the Instagram with with the red texted button](https://photos.google.com/share/AF1QipNz7bdVSbg8sXa_EhmtGegTudXVXwwI0U6UFN7x5WadH57WmU_fwPrdnnqW-JfCwQ?key=ajNmcFVWbGdTdTFUV3dISGduZ2Fua3owbjdFVjJ3), and still didn't work, unfortunately. I also did get the toast message "Root not granted!" when tapping the "Kill & Launch Instagram" button. 

In the video provided, did I do anything wrong? I also tried it, where I patched the IGExperiements app first and then patched it with the Instagram app, but that also didn't work. [And I patched the "Installed" IGExperiments App with itself instead of doing it through the APK](https://photos.google.com/share/AF1QipO9MpNrsx-y1LEO1d43SMrTlOSs7r8LW7qITt4mDbzUDvChfs1fpRRzOhI6vn0KQw?key=bFRPVjBmZ0dNXzU0NXVkMGJwRk1XVlVqaF9CMUZB), but that also didn't work.

Hope this helps provide enough information.

Thanks man!

**Comment by ReSo7200** [comment]
Hey, sorry to hear that.

Tbh it's the same case with my non-rooted phone here.

It's strange though it was working before, can you try one of the older version? 1.0?

**Comment by ReSo7200** [comment]
@xHookman I guess there's something wrong with the code.

I had this issue since 2.0 thought it's my phone only.

Since then, I started to patch it manually.

Can you check the code plz?

Issue -> root is not granted on non-rooted devices (using LSPatch)

**Comment by princawa** [comment]
> Hey, sorry to hear that.
> 
> Tbh it's the same case with my non-rooted phone here.
> 
> It's strange though it was working before, can you try one of the older version? 1.0?

Just tried it with IGExperiment v279.0.0.0.10, and it worked on that same IG Version at the time! I didn't even need to patch the IGExperiments with itself. I then tried to see if it would work with IGExpirments V2.0, and it did not. I totally agree that V2.0 or above isn't working with LSPatch. But any older IGExperiement versions are working properly with LSPatch.

**Comment by ReSo7200** [comment]
Yup, thx...

Waiting for any new updates to fix this issue, I will try to but I am rly busy rn maybe next week.

**Comment by princawa** [comment]
Hey just a heads up, I'm a Tech YouTuber. My channel is called "[HowToMen](https://www.youtube.com/@howtomen)" and the reason I'm saying this is because I'm planning on showing off your app in my next video. It would be awesome if you could get the update pushed out by next week cause I'm sure there's going to be a swarm of people that will begin to download your app and I just want them to be able to get a good experience out of it. :) thanks man!

**Comment by salmanmemon7** [comment]
> Hey just a heads up, I'm a Tech YouTuber. My channel is called "[HowToMen](https://www.youtube.com/@howtomen)" and the reason I'm saying this is because I'm planning on showing off your app in my next video. It would be awesome if you could get the update pushed out by next week cause I'm sure there's going to be a swarm of people that will begin to download your app and I just want them to be able to get a good experience out of it. :) thanks man!

t.me/instasmash

**Comment by ReSo7200** [comment]
Hey!

We have found a better solution to the Non-Rooted devices, I will be releasing a pull request within 48 Hours.

Hope it works with everyone, for the ones that it won't work with them I will release a version that only does support 301.0.0.0.103

**Comment by ReSo7200** [comment]
Hi everyone, check the new Pull request and if there are any issues plz report them!

thx :)

**Comment by ReSo7200** [comment]
Hi again, so we figured a way to make it fully work with LSPatch.

Instead of patching it with the module as embed, Patch it with the Local option, then add the module in the Module scope!

Plz close this if you don't have any questions...

**Comment by salmanmemon7** [comment]
Easiest way to update without doing anything
Just enable 
Is employee command
And 
Download new apk of Instagram and 
Download apktool
Zipalign the download apk and update the zipalign apk and you are updated to new version
Note this will work until you can't clear chache 
If you clear chache your Devloper settings will go away and you get back to normal Instagram

**Comment by ReSo7200** [comment]
Thanks, we already know this, we updated the readme.

Another thing it would be easier just to patch instagram locally because that wouldn't need you to zipalign anything :)

**Comment by salmanmemon7** [comment]
Thanks for replying but my comments is just to make easier way. Many new user don't know how lspatch works. Best of luck

**Comment by ReSo7200** [comment]
Thanks to you.

I might do a recording, I guess that would help everyone.

**Comment by salmanmemon7** [comment]
I also do the same work i open Devloper settings of every version and uplod to my GitHub respotriy 
For Instagram 
https://github.com/salmanmemon7/Ig-internal-
For Threads https://github.com/salmanmemon7/Threads

**Comment by ReSo7200** [comment]
#14 This will fix this issue
