### ISSUE TITLE
Support for all Instagram versions

### ISSUE THREAD

**Issue by Swakshan** [xHookman/IGexperiments#12]
Hi, I know a better way to enable the developer/experiment options that supports all the versions ( past, present, future*) and the cherry on top is, this method doesn't require to modify the apk file

**Comment by ReSo7200** [comment]
Hi, open a pull request then!

We would really appreciate your contribution.

**Comment by Swakshan** [comment]
Unfortunately I'm not good with xposed module, but here is the method I was talking about.
Basically Instagram stores all the user's developer/experiments overrides in ***data/data/com.instagram.android/files/mobileconfig/mc_overrides.json*** in json format.
The data will be of the form ***{"feature code:":["sub category: : value"],....."_qe_overrides_":[]}***
*28538* is the feature code for _"Employee Mode"_ . All we need to do is check if the key ***"28538:":["0: : true"],***  is present in the file, if not present, add it in the file and if the file itself isnt present, create the file and add the key in the above mentioned format

**Comment by ReSo7200** [comment]
Hey, we checked this method.
unfortunately, with each new update the class which holds this json file changes.

so it would be the same problem.

**Comment by Swakshan** [comment]
Class ?? What I'm trying to say is We don't need to modify anything in the app, no need to inject anything.

All we need to do is just check if the json is present in the folder .../files/mobileconfig. If it doesn't exist create a new json file, and If it exists check if the above mentioned key pair exists

**Comment by ReSo7200** [comment]
I get you but, how do we do that?

Because xposed modules works only by hooking into a method and changing it.

The thing you want can't be achieved with a xposed module...

**Comment by Swakshan** [comment]
I positive we can. I made a test version (unfortunately I dont have the code with me). 

I hooked MainActivity onload function and then checked if the file exists and so on.

**Comment by ReSo7200** [comment]
Ok thx for tip, we will try that.
