### ISSUE TITLE
App freezes 

### ISSUE THREAD

**Issue by Roitsquad** [xHookman/IGexperiments#15]
Sir app get's freeze I'm on Android 13 don't know why please fix it

**Comment by ReSo7200** [comment]
Hi, can you please provide more information?

Are you using a rooted or a non rooted device?

**Comment by Roitsquad** [comment]
Yes in using rooted device

**Comment by Roitsquad** [comment]
If it's possible may you provide back up with Neo back up

**Comment by ReSo7200** [comment]
Can you please tell me in which part it freezes?

Have you enabled the module?

**Comment by ReSo7200** [comment]
Please share a screenshot of the module.

**Comment by Roitsquad** [comment]
App not starting up

**Comment by Roitsquad** [comment]
When I click it freezes

**Comment by Roitsquad** [comment]
> Please share a screenshot of the module.

![Uploading Screenshot_20230920-175131_Shell.png…]()

**Comment by ReSo7200** [comment]
Please note that I have tested it on 3 Rooted Devices, I didn't face this issue.

Can you check if you have gave root access and enabled the module?

If yes can you share the logs from LSPosed etc...

**Comment by ReSo7200** [comment]
I am afraid that I can't see the screenshot, as it says it's uploading.

**Comment by Roitsquad** [comment]
> Please note that I have tested it on 3 Rooted Devices, I didn't face this issue.
> 
> Can you check if you have gave root access and enabled the module?
> 
> If yes can you share the logs from LSPosed etc...

[log.zip](https://github.com/xHookman/IGexperiments/files/12672989/log.zip)

**Comment by Roitsquad** [comment]
![Screenshot_20230920-175131_Shell](https://github.com/xHookman/IGexperiments/assets/63774730/3d3c2370-fd31-4ff2-a956-e93c7a6d2991)

**Comment by ReSo7200** [comment]
Thanks for providing us with the logs, I will check it and get back to you!

**Comment by ReSo7200** [comment]
Can you please check this one?

https://github.com/ReSo7200/IGexperiments/blob/master/2.4%20Test.apk

**Comment by ReSo7200** [comment]
Additionally, can you check the LSPatch method?

**Comment by ReSo7200** [comment]
Hi, I just made a test on a rooted android 13, it works just fine.

Please check your side with LSPosed, magisk, etc...
