### ISSUE TITLE
Doesn't even open

### ISSUE THREAD

**Issue by thelastbatman** [xHookman/IGexperiments#16]
I already have installed official installed. Installed the igexperiments app and enabled in lsposed. Restarted my device and enabled Instragram under the patch. Aftwr that neither igexperiments nor Instragram app opens. Uninstalled

**Comment by ReSo7200** [comment]
Please provide us with the logs of lsposed.

**Comment by thelastbatman** [comment]
Btw i tried the older app 2.3. It works
 However latest 2.4 doesn't open at all

**Comment by ReSo7200** [comment]
Thanks for letting us know, can you please provide us with the logs of lsposed?

Furthermore, what is your device's android version?

**Comment by thelastbatman** [comment]
Android version 13 based on android 14
 How to send lsposed logs

**Comment by ReSo7200** [comment]
First please uninstall the current version you have 2.3, then install 2.4

Now enable the module, head to logs section in lsposed then, clear the logs (from the three dots I guess)

Force stop and Launch the module.

Get back to lsposed logs section, there you should be able to see the logs and you will be able to export them.

And let me ask, have you tried to open the module  without having instagram? And try that without enabling the module plz.

**Comment by ReSo7200** [comment]
No logs were sent, tested app on multiple devices it works just fine.
