### ISSUE TITLE
IG Experiment module doesn't open

### ISSUE THREAD

**Issue by thelastbatman** [xHookman/IGexperiments#19]
This is in reference to my earlier post where I had mentioned Ig experiment module 2.4 doesn't even open but 2.3 works.  So i uninstalled 2.3. Thej installed 2.4 version Attaching lsposed logs now. Check

Using miui 14 based on android 13 . 

As long as module is enabled neither Ig experiment module nor Instagram app won't even open. Had to disable the module to make Instagram open. 

[LSPosed_2023-10-08T19_40_04.141772.zip](https://github.com/xHookman/IGexperiments/files/12840890/LSPosed_2023-10-08T19_40_04.141772.zip)

**Comment by ReSo7200** [comment]
there's nothing wrong within the logs.

The thing is, it might be an issue with your device, or set up.

As you can see at the #17 issue, he was able to use the module.

if 2.3 works just fine with you, please wait till the acceptance of 2.4.1 it might fix the issue with you.

**Comment by thelastbatman** [comment]
But then version 2.3 doesn't show my Instagram version. Currently using Instagram 303

**Comment by thelastbatman** [comment]
Hi. 2.4.1 works. It opens. So i need to select only alpha version to patch. It won't work for my play store downloaded stable Instagram?

**Comment by ReSo7200** [comment]
Hi, yes!

It only supports the versions you see within the module.

However, we update that list every 3 days.

And you can update the app with dev options enabled check the read me on the main github page. (you wouldn't need our module anymore)

**Comment by ReSo7200** [comment]
Anything else?

Or should I close this?

**Comment by thelastbatman** [comment]
Okay thanks. Working as of now. You can close

**Comment by ReSo7200** [comment]
Happy to hear that!
