### ISSUE TITLE
Can you update compatibility?

### ISSUE THREAD

**Issue by ReSo7200** [xHookman/IGexperiments#2]
Hey, thanks for this module, I would like to ask, can you plz update it to be compatible with the newest Instagram version?

Edit: no worries, I found the way to update it, I found the class name for the specific version, I will push a pull request...

**Comment by Swakshan** [comment]
Well, you don't need to edit/modify the app for each update.
You can just enable "is_employee" once and for each update, you can just sign it and use, developer options will stay until you uninstall and reinstall the app
