### ISSUE TITLE
Queries 

### ISSUE THREAD

**Issue by thelastbatman** [xHookman/IGexperiments#20]
Hi  .i have two queries regarding the ig Experiment module. 

1. For update you have mentioned Enable "is employee", "employee options", "is employee or test user". 

Under ' is employee or test user ' there are two sub categories - is and is enabled. Both need to be turned on? 

2. For update to new version you have mentioned to -

Disable the Modulde from (magisk, Edxposed, LSposed etc...)
Download and Install a newer version from Apkmirror

After installing new version then would i need to enable the igexperiments module back again from lsposed or let me remain disabled?

**Comment by ReSo7200** [comment]
Hi!

For the first question, turn them on just in case.

For the second question, no, you don't; actually, you mustn't enable the module. That would cause the Instagram app to crash as it would try to hook into a non-existent method and/or classes.

**Comment by thelastbatman** [comment]
So let the module be there in lsposed in disabled state? What if i remove it ?

**Comment by ReSo7200** [comment]
You can too...

**Comment by ReSo7200** [comment]
plz note, u have to disable/remove the module before installing the new version!

**Comment by thelastbatman** [comment]
So i think i get it. I need to keep checking the igexperiments module to see which version of Instagram are currently getting supported and updated. Then download the specific version and disable module then install it. Correct? Because don't think version not mentioned on igexperiments will support

**Comment by ReSo7200** [comment]
1. Install the module and enable it.
2. Select one of the supported versions from the list
3. Download and install it
4. Kill and Launch instagram
5. Enable the specific options( is employee, etc...)
6. Disable or Uninstall the module
7. Go to apkmirror.com Download and install whatever version you want.
