### ISSUE TITLE
LongPressing Home Does Nothing 

### ISSUE THREAD

**Issue by Lg-PWNd** [xHookman/IGexperiments#22]
I followed all the instructions in the wiki
I've redone it three different times with the same results

I step by step followed your instructions and when I get to where I'm supposed to hold the home key

Nothing happens 🤷‍♂️

**Comment by ReSo7200** [comment]
Hi!

Can you confirm if you are using a rooted or a non rooted device?

Have you downloaded one of the compatible instagram versions? (found inside the module)

**Comment by Lg-PWNd** [comment]
Sure
I'm rooted on the latest magisk
Running the latest Lsposed zygisk

Uninstalled the previous version of Instagram completely

Then I installed your module
I used your module to download the correct Instagram
With the in-app linkbutton that uses an intent to open Chrome and download the file

Once the file was downloaded I then uninstalled your module and reboot it again

Then I installed the downloaded Instagram

Then I installed your module and enabled it in lsposed

Then I rebooted again

Then I use the APK selection menu in your module to once again select the downloaded version

Then I hit the kill and launch Instagram button

Instagram comes up perfectly fine
At this point the expected behavior would be that I long press the home button at the bottom of my screen and it should open a developer page

However my first go at with this
The only thing that happened when I long press the home button was Google's stupid assistant comes up

So I went into my settings and Android settings and I searched for home

Found the setting that enables long pressing the home button to get the assistant
And I turned that off
Rebooted went through all the steps to kill and launch the app again

And now I hold the home key and nothing happens at all
There's a chance this could be operator error here

But I really have no idea
Is there a way to launch the intent to get the developers options without having to use the home button ??

**Comment by Lg-PWNd** [comment]
![Screenshot_20231020-122307_Arrow Launcher](https://github.com/xHookman/IGexperiments/assets/25210473/7e04581d-cd4f-4ab9-a942-c8f6568a7ce7)


I'm also using a custom ROM
Arrow OS
Android version 13

And my device is Motorola G7 Plus
Codenamed lake

**Comment by Lg-PWNd** [comment]
Oh I don't know if it matters but I forgot something in there too when I downloaded the Instagram using your module and then I uninstalled your module and rebooted I then logged into that Instagram before I reinstalled your module

**Comment by ReSo7200** [comment]
oh dear, you are messing everything up...

first, after you downloaded and installed the specific compatible Instagram version (use beta - stable has some issues) You mustn't uninstall our module...

you just open the module, and press on the kill Instagram button.

now once you sign in, you press and hold on the instagram home button not the android phone home button :)

now if you want to support newer versions, just enable the options listed in the guide, uninstall our module or disable it from xposed, then install a newer version from apkmirror...

**Comment by Lg-PWNd** [comment]
Well I thought maybe there was an issue with the arch
Im on 64 bit arm
So I went ahead and downloaded the regular armv7a Instagram apk

But I installed that it's still no dice same behavior exact same behavior 🤷‍♂️😔

**Comment by ReSo7200** [comment]
?? I Don't get you...

have you checked my comment above?

I guess I have to create a video recording explaining how to do it...

there's no issue with the module, if you didn't know how to use it; wait for the video recording it would be available in 48 to 72 hours...

**Comment by Lg-PWNd** [comment]
> oh dear, you are messing everything up...
> 
> first, after you downloaded and installed the specific compatible Instagram version (use beta - stable has some issues) You mustn't uninstall our module...
> 
> you just open the module, and press on the kill Instagram button.
> 
> now once you sign in, you press and hold on the instagram home button not the android phone home button :)
> 


> now if you want to support newer versions, just enable the options listed in the guide, uninstall our module or disable it from xposed, then install a newer version from apkmirror...


Okay awesome I'm going to try this again I'm going to uninstall your module uninstall these apk

Then I'm going to reboot
Then I'm going to install the module first
Then I'm going to use the module to download the beta
Then I'm going install the beta
Open it
And then I go back to the module and hit the kill button right 
Then it'll relaunch Instagram for me and I'll have to sign in

Once I sign in then I hold the Instagram home button that looks like a little house in the far bottom left corner of the screen
 
Am I getting this right  🤷‍♂️

I sure appreciate your time

**Comment by Lg-PWNd** [comment]
> ?? I Don't get you...
> 
> have you checked my comment above?
> 
> I guess I have to create a video recording explaining how to do it...
> 
> there's no issue with the module, if you didn't know how to use it; wait for the video recording it would be available in 48 to 72 hours...

Yeah evidently I did not catch that you had already given me instructions

Sorry

**Comment by ReSo7200** [comment]
you don't have to reboot your device, no one mentioned that in the guide.

and you don't have to open instagram once you installed it, just head to the module and press the kill button, it would open it for you...

**Comment by Lg-PWNd** [comment]
> you don't have to reboot your device, no one mentioned that in the guide.
> 
> and you don't have to open instagram once you installed it, just head to the module and press the kill button, it would open it for you...

Okay look ReSo
I am not a noob
You don't have to talk down to me because I'm having trouble understanding how to use your tool

I build tools of my own
I am LgPWNd @ A-Team Digital Solutions
https://t.me/A_Team_Digital_Solutions

We build Android and all kinds of cool stuff to go with it so I don't really appreciate being talked to like I'm an elementary student

However following your instructions and then following the instructions you've given me in your comments still has not resolved this issue sir

Here let me paint a picture for you
Geeze
I screen recorded the whole episode
Have a look man

https://www.instagram.com/reel/CyoUeIsAiW9/?igshid=MTc4MmM1YmI2Ng==

I believe I am following your instructions precisely

And forgive me if your shit doesn't work and I try to troubleshoot things before I raise a fucking issue
🤷‍♂️
At this point I don't care if it works or not
As far as I can tell your shit's broken.
And I know the next little excuse you want to throw out there is that I'm running a custom ROM
I got a lot of that shit from all you guys over there on XDA all the time

Now if you want to figure out why your shit don't work on this device I'm more than willing to troubleshoot this and walk through it all with you
But there's no way you're going to keep talking down to me like that there's no reason to be condescending

**Comment by ReSo7200** [comment]
Hmm, chill I didn't say anything + I am sure our module works like a charm.

![Screenshot_20231020_212542_Instagram](https://github.com/xHookman/IGexperiments/assets/47777771/16e1d3a7-ba48-4ec9-8dce-c30b2193b4b9)

I won't be helping you on this tbh, you are insulting us and our module.

thx and have a nice day + you will see a video recording in the next days...

**Comment by Lg-PWNd** [comment]
> Hmm, chill I didn't say anything + I am sure our module works like a charm.
> 
> ![Screenshot_20231020_212542_Instagram](https://user-images.githubusercontent.com/47777771/277022018-16e1d3a7-ba48-4ec9-8dce-c30b2193b4b9.jpg)
> 
> I won't be helping you on this tbh, you are insulting us and our module.
> 
> thx and have a nice day + you will see a video recording in the next days...

Charly Pecquery 🥱

I just showed you that what you told me to do did not work on this device + all you can do is turn around and claim there's nothing wrong with your module ???

Listen man I'm not saying there's anything wrong with your module + if it works fine on your phone.... That's great man  + I'm just saying it doesn't freaking work on this device man
And you were kind of being a jerk

You Said :
_______________________________________________
?? I Don't get you...

have you checked my comment above?

I guess I have to create a video recording explaining how to do it...

there's no issue with the module, if you didn't know how to use it; wait for the video recording it would be available in 48 to 72 hours...
_______________________________________________

                  And then:
_______________________________________________
you don't have to reboot your device, no one mentioned that in the guide.

and you don't have to open instagram once you installed it, just head to the module and press the kill button, it would open it for you...
_______________________________________________

🤷‍♂️And of course you can't see where your words come across rude 🤷‍♂️
                                            +
Here I was trying to be a nice guy and tell you that your stuff's not working on this model and device
It's okay your module was a curiosity not a necessity 👍

**Comment by ReSo7200** [comment]
bro, when I said "?? i don't get you" that cause really i didn't get you

not because I am some sort of jerk or whatever

thx again and have a nice day

**Comment by xHookman** [comment]
> > you don't have to reboot your device, no one mentioned that in the guide.
> > and you don't have to open instagram once you installed it, just head to the module and press the kill button, it would open it for you...
> 
> Okay look ReSo I am not a noob You don't have to talk down to me because I'm having trouble understanding how to use your tool
> 
> I build tools of my own I am LgPWNd @ A-Team Digital Solutions https://t.me/A_Team_Digital_Solutions
> 
> We build Android and all kinds of cool stuff to go with it so I don't really appreciate being talked to like I'm an elementary student
> 
> However following your instructions and then following the instructions you've given me in your comments still has not resolved this issue sir
> 
> Here let me paint a picture for you Geeze I screen recorded the whole episode Have a look man
> 
> https://www.instagram.com/reel/CyoUeIsAiW9/?igshid=MTc4MmM1YmI2Ng==
> 
> I believe I am following your instructions precisely
> 
> And forgive me if your shit doesn't work and I try to troubleshoot things before I raise a fucking issue 🤷‍♂️ At this point I don't care if it works or not As far as I can tell your shit's broken. And I know the next little excuse you want to throw out there is that I'm running a custom ROM I got a lot of that shit from all you guys over there on XDA all the time
> 
> Now if you want to figure out why your shit don't work on this device I'm more than willing to troubleshoot this and walk through it all with you But there's no way you're going to keep talking down to me like that there's no reason to be condescending

Okay okay first CAAALMM DOOOWN GUYS PLEASE!!

So if you uninstall the module and instagram app (so we start from zero).

1. Install the module without enable it (because you don't have ig)
2. Install instagram from the module (choose arm64 version on apkmirror)
3. Open lsposed and enable the module
4. CLOSE and open the module (otherwise it still disabled)
5. Choose the correct version and click on Kill & Launch Instagram
6. On Instagram, long press the home button (next to the magnifying glass at bottom left corner)

If it still does not work, do you have logs from lsposed manager ?

**Comment by Lg-PWNd** [comment]
> Okay okay first CAAALMM DOOOWN GUYS PLEASE!!
> 
> So if you uninstall the module and instagram app (so we start from zero).
> 
> 1. Install the module without enable it (because you don't have ig)
> 2. Install instagram from the module (choose arm64 version on apkmirror)
> 3. Open lsposed and enable the module
> 4. CLOSE and open the module (otherwise it still disabled)
> 5. Choose the correct version and click on Kill & Launch Instagram
> 6. On Instagram, long press the home button (next to the magnifying glass at bottom left corner)
> 
> If it still does not work, do you have logs from lsposed manager ?

I will try this again today just to see if it works but I really don't care honestly because like I said before it was just a curiosity not a necessity
The only reason it was a curiosity is because I developed Android and well I'm also a cyber security researcher

My colleagues rebuilt your project yesterday with ls patch and have been playing with it a little bit
Myself I was curious about all the SSH RSA key stuff in your code
So we disabled SSL pinning too 🤷‍♂️

Was only even interested in your module because I'm a cybersecurity researcher and I've been going after scammers on the Meta platform Facebook and Instagram
And thought I might be able to use your module to get more information about  the criminal that is using the stolen account....

But yes I will try this again later today and if it still doesn't work I will try to get you some detailed logs 👍
Because as a fellow Android developer I do believe in helping someone troubleshoot their code so that it can be universal across devices 🤷‍♂️

Until they get all big headed and pig-headed
because they think they're popular or think they're fucking special 
then I'm usually done with the whole situation
🖕🫵Reso7200 ur a ❄️
