### ISSUE TITLE
Instagram crash when select album

### ISSUE THREAD

**Issue by wongcheehong** [xHookman/IGexperiments#25]
I am using rootless method. I have try to use the same apk without patching no issue at all. After patching, I cannot select other albums when posting. Try to click the button as shown in the screenshot below, it crash when I clicked it
![Screenshot_20231028_131056_Instagram](https://github.com/xHookman/IGexperiments/assets/11075969/72f9210c-e2a3-4b8b-b471-7cb371e21d63)

**Comment by ReSo7200** [comment]
Hi, can you please confirm if the Instagram version you are using is 306.0.0.0.97?

**Comment by ReSo7200** [comment]
Hi again, I can confirm that the issue was with version 306.0.0.0.97.

I have updated the supported versions within the module, please open the module and check for the new versions.

I will leave this open until you confirm that the issue has been resolved.

**Comment by wongcheehong** [comment]
yes, resolved already with the latest version

**Comment by ReSo7200** [comment]
Thanks for the confirmation!

This issue will be closed.
