### ISSUE TITLE
Threads add to story linking is not working anymore after patching

### ISSUE THREAD

**Issue by wongcheehong** [xHookman/IGexperiments#26]
After patched the instagram, the Threads's add to story and feed is not working anymore. 

![20231028_162510](https://github.com/xHookman/IGexperiments/assets/11075969/8f2f4810-fc30-48e5-ad6b-fecc25574694)

**Comment by ReSo7200** [comment]
where do I find that?

**Comment by ReSo7200** [comment]
No worries I got you.

**Comment by wongcheehong** [comment]
It is in Threads ap. This is when you click on the share button on the thread post

**Comment by wongcheehong** [comment]
I found the deep linking not working also. Previously you can open instagram app directly from link. Now it direct me to web browser instead. I think the patch messed up the deep linking.

**Comment by ReSo7200** [comment]
> It is in Threads app, this is when you click on the share button on on thread post

so basically I found a solution for this, you have to patch it with LSPatch as a local "like instagram but don't apply any module on it"

**Comment by ReSo7200** [comment]
> I found the deep linking not working also. Previously you can open instagram app directly from link. Now it direct me to web browser instead. I think the patch messed up the deep linking.

please make sure to enable those:

![Screenshot_20231028_115524_Settings](https://github.com/xHookman/IGexperiments/assets/47777771/15147835-0159-4f66-84e1-81dd6912a2f6)

**Comment by wongcheehong** [comment]
Okay, I have try to remove the module in LSPatch and enable all the supported web address, but the only this address "www.instagram.com" cannot be enable, it disable after I enable it.

**Comment by wongcheehong** [comment]
I found that, in unmodified apk, these option is enabled by default and cannot be toggle
![Screenshot_20231028_170547_Settings](https://github.com/xHookman/IGexperiments/assets/11075969/e0ec41b5-5049-4c06-bd3a-40ead43cbe67)

**Comment by ReSo7200** [comment]
> Okay, I have try to remove the module in LSPatch and enable all the supported web address, but the only this address "www.instagram.com" cannot be enable, it disable after I enable it.

I see, it's strange tbh.

I will try somethings out.

**Comment by ReSo7200** [comment]
did the threads app work?

**Comment by wongcheehong** [comment]
> did the threads app work?

No either

**Comment by ReSo7200** [comment]
> > did the threads app work?
> 
> No either

it did work on my end, have you patched it with local mode?

**Comment by wongcheehong** [comment]
yes it is in local mode. And I even uninstall and patch it in local mode and did not embed module

**Comment by wongcheehong** [comment]
Does your web address "www.instagram.com" still enabled after navigate away and come back?

**Comment by ReSo7200** [comment]
> yes it is in local mode. And I even uninstall and patch it in local mode and did not embed module

strange that it does work on my end.

I will check on it once I get back home.

**Comment by ReSo7200** [comment]
I am back.

so for the first issue, you have to make sure that you have done these steps:

1. install threads from google play store
2. go to LSPatch and add new patch
3. select patch mode as Local
4. start patch and uninstal and install the patched threads

I tried it and it works.

now for the second issue, as I can see when I tried to share a link from instagram it would be using "instagram.com" and not "www.instagram.com" in which not enabling it won't harm.

please try those, have a nice day.

**Comment by wongcheehong** [comment]
wow I just tried, it work already. Thank you so much for your help

**Comment by ReSo7200** [comment]
ok thanks for confirming!
