### ISSUE TITLE
Can't load music list in music sticker

### ISSUE THREAD

**Issue by wongcheehong** [xHookman/IGexperiments#27]
Instagram Version 308.0.0.0.10
Rootless method (local patch)

![Screenshot_20231030_023444_Instagram](https://github.com/xHookman/IGexperiments/assets/11075969/92da5ed3-a032-4eac-b8dd-cd5eeff6878b)

**Comment by ReSo7200** [comment]
bro look, we can't fix every feature, we are just doing this module to enable developer options.

basically in the last issues, it was about instagram versions.

please try to use a stable version.
