### ISSUE TITLE
Guide or tutorials? Doubts..

### ISSUE THREAD

**Issue by donete7** [xHookman/IGexperiments#28]
[using Google translator]
Hello, I just downloaded and installed this mod. The IGEX apk has a very direct step-by-step guide without much explanation. I didn't quite understand when you said: "Kill and launch ig / 4 long press the home button and enjoy"
  I looked for a step by step guide but couldn't find it, could anyone help me? Does this mod still work today? I'm confused.
I didn't find the options, if there is a way to view without leaving a trace, save the instant photos from the dm...
Thank you in advance to anyone who can help me. ;)

**Comment by ReSo7200** [comment]
Hi!

Hope you are having a beautiful day!

Yes, the mod works, look I will do some screen recordings for both rooted and non-rooted devices and send you the links once I upload them. (I have bad internet speed rn so it will take some time :(   

Now for the guide, if you are using a rooted device; there's a button in the module that would kill Instagram and open it.

If you are using a non-rooted one; you have to force stop Instagram, then open it.

Now on both, to open the developer options, you have to click and hold on the Instagram home button..

Please note, I will be updating the supported Instagram versions right away, you will see them in one hour or two, thanks!!

**Comment by donete7** [comment]
Thanks! I'm having a great day and I wish you the same. What a quick response! I'm using root, Android 12/ SAM A11.
I would be very grateful if you could send me the video! And I downloaded the version that appears in the mod (307.0.034...)

**Comment by donete7** [comment]
What home button is that? Could you send me a screenshot? And could you show me which functions are active? I'm interested in the function of saving photos/video snaps (single view) that are sent to me in DM. Could you tell me if this mod has this function? Thank you again :)

**Comment by ReSo7200** [comment]
Sure, here's a screenshot:

![image](https://github.com/xHookman/IGexperiments/assets/47777771/05be6e3f-173b-4b0b-bf49-a59cc9d717a9)


Unfortunately, our mod is only supposed to open the developer options; you can find and try to play with the values there as you want; however, we don't recommend that :(

I can suggest you Instander, Honista, Aeroinsta for that features :)

**Comment by ReSo7200** [comment]
I am afraid that I won't be able to update the supported versions in the module until Monday, as I am traveling rn and my laptop isn't helping that much :(  I will try to upload the recordings as soon as possible. :)

Though you can use the guide to update to whatever version you want...

**Comment by donete7** [comment]
I researched this Instander, but I couldn't download its version on the website. If it wasn't too much to ask, could you please download it for me? Is it a root mod too? I haven't seen anything about this specification. Are any of these others also root or unroot?
And I imagined it was this miniature house button, but I pressed it and nothing appeared to me :/

**Comment by ReSo7200** [comment]
> I researched this Instander, but I couldn't download its version on the website. If it wasn't too much to ask, could you please download it for me? Is it a root mod too? I haven't seen anything about this specification. Are any of these others also root or unroot? And I imagined it was this miniature house button, but I pressed it and nothing appeared to me :/

It's a modded Instagram, here's the official link: https://thedise.me/instander/repo/

For our module, You must check that you have enabled it using LSPosed, Edexposed, etc...

And force stop instagram and open it.

I guess the recording would help you, give me 30 minutes...

**Comment by ReSo7200** [comment]
https://youtu.be/9FxEFLCSA-8

Here you go, please note that I didn't have to force stop Instagram as the first time I ran it, it was having the module on...

**Comment by donete7** [comment]
Perfect!! Great! I just watched the video here and I think I did it exactly like this lol except I opened Instagram and then closed it and went to the mod and clicked on the "kill ...." option and then went back to IG and pressed it and none of that appeared. I'll test it and come back later to let you know if it worked! Now with video it’s much better to understand! :)

**Comment by ReSo7200** [comment]
@donete7 Hi! can you please confirm if it works?

**Comment by ReSo7200** [comment]
No response from the user.
