### ISSUE TITLE
Not working on KernelSU and LSPosed

### ISSUE THREAD

**Issue by nitanmarcel** [xHookman/IGexperiments#29]
I'm using it with KernelSu and LSPosed and I cannot get the module to work, there's no popup telling me that something is wrong, not even when trying to inject the wrong version.

I've tried with both stable and alpha but it doesn't seem to work.

I tried force stopping Instagram, clearing app data but nothing made the module work
[LSPosed_2023-11-25T12_12_49.745289.zip](https://github.com/xHookman/IGexperiments/files/13463645/LSPosed_2023-11-25T12_12_49.745289.zip)
[LSPosed_2023-11-25T12_13_20.514282.zip](https://github.com/xHookman/IGexperiments/files/13463646/LSPosed_2023-11-25T12_13_20.514282.zip)

![IMG_20231125_122243](https://github.com/xHookman/IGexperiments/assets/41646249/776399d2-a92d-4f10-97dc-4d44158eaed3)
![Screenshot_20231125-122257_Shell](https://github.com/xHookman/IGexperiments/assets/41646249/faa25b7b-73b4-4cbf-a18b-cb800dc62df1)

**Comment by ReSo7200** [comment]
Hi, hope you are having a good day!

So once you log into your Instagram account and try to open the developer options by holding on the Instagram home key, it doesn't show anything?

**Comment by nitanmarcel** [comment]
> Hi, hope you are having a good day!
> 
> So once you log into your Instagram account and try to open the developer options by holding on the Instagram home key, it doesn't show anything?

Nope.

I wonder does the module uses any restricted APIs?

[logs-2023-11-25-12-34-01.zip](https://github.com/xHookman/IGexperiments/files/13463736/logs-2023-11-25-12-34-01.zip)

**Comment by ReSo7200** [comment]
> > Hi, hope you are having a good day!
> > So once you log into your Instagram account and try to open the developer options by holding on the Instagram home key, it doesn't show anything?
> 
> Nope.
> 
> I wonder does the module uses any restricted APIs?
> 
> [logs-2023-11-25-12-34-01.zip](https://github.com/xHookman/IGexperiments/files/13463736/logs-2023-11-25-12-34-01.zip)

Nope, you can see the source code.

I saw the logs, and the only errors within the logs were that the method wasn't found and I guess that happened when you tried it with unsupported version...

I will send you a version which logs some data so we can check, I will send it once I reach home. for now you can use the igexperiments patcher on pc if you want.

**Comment by nitanmarcel** [comment]
> > > Hi, hope you are having a good day!
> > > So once you log into your Instagram account and try to open the developer options by holding on the Instagram home key, it doesn't show anything?
> > 
> > 
> > Nope.
> > I wonder does the module uses any restricted APIs?
> > [logs-2023-11-25-12-34-01.zip](https://github.com/xHookman/IGexperiments/files/13463736/logs-2023-11-25-12-34-01.zip)
> 
> Nope, you can see the source code.
> 
> I saw the logs, and the only errors within the logs were that the method wasn't found and I guess that happened when you tried it with unsupported version...
> 
> I will send you a version which logs some data so we can check, I will send it once I reach home. for now you can use the igexperiments patcher on pc if you want.

Thanks will wait.

**Comment by ReSo7200** [comment]
Can you please try this one?

https://github.com/ReSo7200/IGexperiments/blob/Dev-Pur/IGexp%20DEV.apk

First clear the LSPosed logs so it can be clear.

**Comment by nitanmarcel** [comment]
> Can you please try this one?
> 
> https://github.com/ReSo7200/IGexperiments/blob/Dev-Pur/IGexp%20DEV.apk
> 
> First clear the LSPosed logs so it can be clear.

[LSPosed_2023-11-25T15_42_19.546239.zip](https://github.com/xHookman/IGexperiments/files/13464242/LSPosed_2023-11-25T15_42_19.546239.zip)

**Comment by ReSo7200** [comment]
Ok I checked the logs, it seems it hooks into Instagram, takes the version and the classes to be hooked into, but it can't replace the method.
![image](https://github.com/xHookman/IGexperiments/assets/47777771/858b206d-c772-4cb0-8359-3b92ba91df7f)

Please use this version and provide us with the logs again.

https://github.com/ReSo7200/IGexperiments/blob/Dev-Pur/IGExp%20Dev%202.apk

**Comment by nitanmarcel** [comment]
> Ok I checked the logs, it seems it hooks into Instagram, takes the version and the classes to be hooked into, but it can't replace the method. ![image](https://private-user-images.githubusercontent.com/47777771/285595565-858b206d-c772-4cb0-8359-3b92ba91df7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjE2MjIsIm5iZiI6MTcwMDkyMTMyMiwicGF0aCI6Ii80Nzc3Nzc3MS8yODU1OTU1NjUtODU4YjIwNmQtYzc3Mi00Y2IwLTgzNTktM2I5MmJhOTFkZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE0MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOGU3NDRmODIyZTMwOTAzYTQzOTUxZjc0OTU4ZWY1MTFiNDcxOGMxNWIxNjUzYWRkYzI1NDc3NjY3MTFlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MZO4dmkiXgCBKPLqHsr_1uobFaO3PL1cDmpU1JiJXKY)
> 
> Please use this version and provide us with the logs again.
> 
> https://github.com/ReSo7200/IGexperiments/blob/Dev-Pur/IGExp%20Dev%202.apk

Seems that the method is trying to hook doesn't exist, even if I'm using the same version. Maybe it requires an exact version of the apk, as in for example a bundle instead of an apk

[LSPosed_2023-11-25T16_09_27.606046.zip](https://github.com/xHookman/IGexperiments/files/13464295/LSPosed_2023-11-25T16_09_27.606046.zip)

**Comment by ReSo7200** [comment]
> > Ok I checked the logs, it seems it hooks into Instagram, takes the version and the classes to be hooked into, but it can't replace the method. ![image](https://private-user-images.githubusercontent.com/47777771/285595565-858b206d-c772-4cb0-8359-3b92ba91df7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjE2MjIsIm5iZiI6MTcwMDkyMTMyMiwicGF0aCI6Ii80Nzc3Nzc3MS8yODU1OTU1NjUtODU4YjIwNmQtYzc3Mi00Y2IwLTgzNTktM2I5MmJhOTFkZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE0MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOGU3NDRmODIyZTMwOTAzYTQzOTUxZjc0OTU4ZWY1MTFiNDcxOGMxNWIxNjUzYWRkYzI1NDc3NjY3MTFlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MZO4dmkiXgCBKPLqHsr_1uobFaO3PL1cDmpU1JiJXKY)
> > Please use this version and provide us with the logs again.
> > https://github.com/ReSo7200/IGexperiments/blob/Dev-Pur/IGExp%20Dev%202.apk
> 
> Seems that the method is trying to hook doesn't exist, even if I'm using the same version. Maybe it requires an exact version of the apk.
> 
> [LSPosed_2023-11-25T16_09_27.606046.zip](https://github.com/xHookman/IGexperiments/files/13464295/LSPosed_2023-11-25T16_09_27.606046.zip)

That what I thought, but I already tried it on Samsung A9 2018, and it works with no issues...

**Comment by nitanmarcel** [comment]
> > > Ok I checked the logs, it seems it hooks into Instagram, takes the version and the classes to be hooked into, but it can't replace the method. ![image](https://private-user-images.githubusercontent.com/47777771/285595565-858b206d-c772-4cb0-8359-3b92ba91df7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjE2MjIsIm5iZiI6MTcwMDkyMTMyMiwicGF0aCI6Ii80Nzc3Nzc3MS8yODU1OTU1NjUtODU4YjIwNmQtYzc3Mi00Y2IwLTgzNTktM2I5MmJhOTFkZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE0MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOGU3NDRmODIyZTMwOTAzYTQzOTUxZjc0OTU4ZWY1MTFiNDcxOGMxNWIxNjUzYWRkYzI1NDc3NjY3MTFlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MZO4dmkiXgCBKPLqHsr_1uobFaO3PL1cDmpU1JiJXKY)
> > > Please use this version and provide us with the logs again.
> > > https://github.com/ReSo7200/IGexperiments/blob/Dev-Pur/IGExp%20Dev%202.apk
> > 
> > 
> > Seems that the method is trying to hook doesn't exist, even if I'm using the same version. Maybe it requires an exact version of the apk.
> > [LSPosed_2023-11-25T16_09_27.606046.zip](https://github.com/xHookman/IGexperiments/files/13464295/LSPosed_2023-11-25T16_09_27.606046.zip)
> 
> That what I thought, but I already tried it on Samsung A9 2018, and it works with no issues...

Can you backup the instagram apk and post it somewhere?

https://github.com/alexrintt/kanade/releases

**Comment by ReSo7200** [comment]
Here you go, I used the Patcher for this:

https://drive.google.com/file/d/1o16bX3xwVaFo_oIh6BKR1M3DYEtL6Wj8/view?usp=sharing

**Comment by xHookman** [comment]
When i use the patcher i get the X.19o class to hook ? Not X.19k :/ Can you enable the hecker mode and may be try with X.19o, A00 and X.0pg please ?
I tried with this apk : https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-310-0-0-0-153-release/instagram-310-0-0-0-153-android-apk-download/

**Comment by nitanmarcel** [comment]
> When i use the patcher i get the X.19o class to hook ? Not X.19k :/ Can you enable the hecker mode and may be try with X.19o, A00 and X.0pg please ? I tried with this apk : https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-310-0-0-0-153-release/instagram-310-0-0-0-153-android-apk-download/

X.19o works fine. For some reason IGExperiments says it patches X.19k

![Screenshot_20231127-140223_IGexperiments](https://github.com/xHookman/IGexperiments/assets/41646249/4118a83c-e957-4c70-877f-5e81f7bd8246)

**Comment by xHookman** [comment]
> > When i use the patcher i get the X.19o class to hook ? Not X.19k :/ Can you enable the hecker mode and may be try with X.19o, A00 and X.0pg please ? I tried with this apk : https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-310-0-0-0-153-release/instagram-310-0-0-0-153-android-apk-download/
> 
> X.19o works fine. For some reason IGExperiments says it patches X.19k
> 
> ![Screenshot_20231127-140223_IGexperiments](https://private-user-images.githubusercontent.com/41646249/285855700-4118a83c-e957-4c70-877f-5e81f7bd8246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwOTg2NDYsIm5iZiI6MTcwMTA5ODM0NiwicGF0aCI6Ii80MTY0NjI0OS8yODU4NTU3MDAtNDExOGE4M2MtZTk1Ny00YzcwLTg3N2YtNWU4MWY3YmQ4MjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE1MTkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMGU2MjVjODAxODJjM2UyMmYwNTQ4M2M2OTI3NmUyYTJmMTJkZDRmMWI3N2E2MjNmMWYyZmEzMTM2NTcwMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rJiqIquQD5EiMuS58qYLEWkl5nmLL6yXrRpUVwrhO5U)

Oh cool ! I think there was an error from us for this version :)
