### ISSUE TITLE
Enabling Employee options doesn't seem to function 

### ISSUE THREAD

**Issue by neostra1ghts** [xHookman/IGexperiments#30]
After following the guide on the GitHub readme
Internal settings are still giving me an error that says: "Internal settings are only accessible to employees and test accounts"
I'm using the alpha 310.0.0.0.153 (Build #538629815)

**Comment by ReSo7200** [comment]
Hi

Please note, you can access developer options by holding on Instagram home button.

if you would like to change some hidden settings, you can by heading to the "MetaConfig Settings & Overrides"

btw, I just updated the supported versions in the module.

Thanks!
