### ISSUE TITLE
Employee option not showing up

### ISSUE THREAD

**Issue by mjain234** [xHookman/IGexperiments#31]
I tried to follow all the process and while trying first time, the developer option won't show up but 2nd time, it worked and now this time, the Employee option doesnt show up in "Meta Config".

Device ~ Realme 2 Pro
 
OS ~ Arrow OS

Android version ~ Android 13

Root Status ~ True

[Lsposed logs](![LSPosed_2024-01-09T12_55_06.228727.zip](https://github.com/xHookman/IGexperiments/files/13870322/LSPosed_2024-01-09T12_55_06.228727.zip))

Here is the [video](https://i.imgur.com/42pAI95.mp4)

**Comment by Mikicrepstudios** [comment]
Same problem on a40 android 12 rooted crdroid 8.2

Exactly same steps, dev options didnt want to work till i enabled hecker mode then it showed, got no employee mode

**Comment by ReSo7200** [comment]
Hey! so sorry for this late response.

This issue is related to the specific Instagram version, I will update the supported versions tonight.

Thanks for using our module, have a nice day :)

**Comment by Mikicrepstudios** [comment]
> Hey! so sorry for this late response.
> 
> 
> 
> This issue is related to the specific Instagram version, I will update the supported versions tonight.
> 
> 
> 
> Thanks for using our module, have a nice day :)

one question, how to reset experiments, i accidentally enabled some profile ones now i cant check profile page and others profile pages

**Comment by ReSo7200** [comment]
> > Hey! so sorry for this late response.
> > This issue is related to the specific Instagram version, I will update the supported versions tonight.
> > Thanks for using our module, have a nice day :)
> 
> one question, how to reset experiments, i accidentally enabled some profile ones now i cant check profile page and others profile pages

At the "Experimentation" section, click on "Delete local overrides".

**Comment by Mikicrepstudios** [comment]
> > > Hey! so sorry for this late response.
> 
> > > This issue is related to the specific Instagram version, I will update the supported versions tonight.
> 
> > > Thanks for using our module, have a nice day :)
> 
> > 
> 
> > one question, how to reset experiments, i accidentally enabled some profile ones now i cant check profile page and others profile pages
> 
> 
> 
> At the "Experimentation" section, click on "Delete local overrides".

thank you so much i will try later

**Comment by ReSo7200** [comment]
Hey again!

So, it appears there's an issue with some of the Instagram versions.

We updated the supported versions; however, the stable version had the same issue, so we recommend you use the beta version from the module.

Thanks!
