### ISSUE TITLE
Unable to open dev options

### ISSUE THREAD

**Issue by Mikicrepstudios** [xHookman/IGexperiments#33]
I today updated to 314.0.0.5.114 beta because i saw that i needed to get beta in issue thread. What should my class nams, method name and other class name be (im kinda confused what to do)

**Comment by ReSo7200** [comment]
Hi, you don't have to put it manually. this version is supported...

**Comment by Mikicrepstudios** [comment]
> Hi, you don't have to put it manually. this version is supported...

uh do i have to update igexperiments or? (if i turn off hecker mode its same - no dev options)

**Comment by ReSo7200** [comment]
> > Hi, you don't have to put it manually. this version is supported...
> 
> uh do i have to update igexperiments or? (if i turn off hecker mode its same - no dev options)

You don't have to update IGEXPERIMENTS.

please try to turn off the hecker Mode, then select the version from the drop menu, click on kill and launch instagram.

if it didn't work, disable and enable the module from Xposed.

**Comment by Mikicrepstudios** [comment]
> > > Hi, you don't have to put it manually. this version is supported...
> > 
> > uh do i have to update igexperiments or? (if i turn off hecker mode its same - no dev options)
> 
> You don't have to update IGEXPERIMENTS.
> 
> please try to turn off the hecker Mode, then select the version from the drop menu, click on kill and launch instagram.
> 
> if it didn't work, disable and enable the module from Xposed.

still same issue

**Comment by ReSo7200** [comment]
can you send me the xposed logs here?

please clear the logs before testing the module.

**Comment by Mikicrepstudios** [comment]
> can you send me the xposed logs here?
> 
> please clear the logs before testing the module.

![Screenshot_20240120-071242_Shell.png](https://github.com/xHookman/IGexperiments/assets/92646867/bf9cdbc1-4fb3-4e39-b583-f985ea465806)

(cannot copy logs so had to screenshot)

**Comment by ReSo7200** [comment]
Hi again!

We will be publishing a new update today; I will notify you once it has been.

You will have to install the new update, clear the LSPosed logs, try it, and export the logs (you don't have to copy it but to export it from the three dots button - though screenshot might work...)

**Comment by Mikicrepstudios** [comment]
okay, just tell me when u release it

**Comment by ReSo7200** [comment]
> okay, just tell me when u release it

Here you go!

https://github.com/xHookman/IGexperiments/releases/tag/v2.5

**Comment by Mikicrepstudios** [comment]
![Screenshot_20240120-113812_Shell.png](https://github.com/xHookman/IGexperiments/assets/92646867/ff86bad7-d4f6-413f-abc6-a7e4c83d3593)

exactly same issue, also lsposed says that upgrade available 2.4.1 and says that im on 2.4.5, app is 2.4.5 too but in release says 2.5 did i not update or you didn't change version or something

**Comment by ReSo7200** [comment]
Thanks for telling me about the versions issue, the 2.4.1 is the exposed rep we will update it later.

for 2.4.5 it was a typo we will fix.

Now back to the issue.

When you head to Instagram, and hold on the home button, it won't show anything?

**Comment by Mikicrepstudios** [comment]
yeah, just refreshes home page

**Comment by ReSo7200** [comment]
ok can you try the Alpha version please? select it from the drop menu.

And just for checking, have you enabled the module on Instagram?

**Comment by Mikicrepstudios** [comment]
yes its selected and same issue
alpha 315.0.0.0.109

**Comment by ReSo7200** [comment]
So sorry it appears there was a bug with the new update, please head to the releases section and redownload the module.

**Comment by ReSo7200** [comment]
the new update mightn't fix your issue but it logs everything so we can help.

**Comment by Mikicrepstudios** [comment]
uh sorry i didnt understand what i have to do

**Comment by ReSo7200** [comment]
> uh sorry i didnt understand what i have to do

Just download the module again from here: https://github.com/xHookman/IGexperiments/releases/tag/v2.5

**Comment by Mikicrepstudios** [comment]
uh im not sure how to send logs because when i click save icon in top right it says "enable document ui" but it give some java error
```
unable to read manifests from {app package here}

unable to invoke virtual method {some stuff here} on a null object refrence
```

**Comment by ReSo7200** [comment]
Just send me a screenshot then

**Comment by Mikicrepstudios** [comment]
```
[ 2024-01-20T12:57:27.815    10375: 24814: 24814 I/LSPosed         ] Loading xposed for com.chacha.igexperiments/10375
[ 2024-01-20T12:57:27.851    10375: 24814: 24814 I/LSPosed-Bridge  ] Loading legacy module com.chacha.igexperiments from /data/app/~~cMT-C-vvE1l7dtPcVCDWfg==/com.chacha.igexperiments-GTgEjI_nxLDATYi42Gt-iQ==/base.apk
[ 2024-01-20T12:57:28.015    10375: 24814: 24814 I/LSPosed-Bridge  ]   Loading class com.chacha.igexperiments.Module
[ 2024-01-20T12:57:28.966    10375: 24814: 24814 W/LSPosed         ] New modules detected, hook preferences
[ 2024-01-20T12:57:43.564     2000: 29730: 29730 I/LSPosed         ] Loaded manager, skipping next steps
[ 2024-01-20T12:57:48.235        0:  4346:  4363 I/lspd            ] Background concurrent copying GC freed 344659(23MB) AllocSpace objects, 12(2608KB) LOS objects, 83% free, 4779KB/28MB, paused 78us,72us total 144.304ms
[ 2024-01-20T12:57:54.955        0:  4346:  4372 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2024-01-20T12:57:54.962        0:  4346:  4374 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2024-01-20T11:57:54.959.log
[ 2024-01-20T12:58:09.045    10250: 29731: 29731 I/LSPosed         ] Loading xposed for com.instagram.android/10250
[ 2024-01-20T12:58:09.066    10250: 29731: 29731 I/LSPosed-Bridge  ] Loading legacy module com.chacha.igexperiments from /data/app/~~cMT-C-vvE1l7dtPcVCDWfg==/com.chacha.igexperiments-GTgEjI_nxLDATYi42Gt-iQ==/base.apk
[ 2024-01-20T12:58:09.268    10250: 29731: 29731 I/LSPosed-Bridge  ]   Loading class com.chacha.igexperiments.Module
[ 2024-01-20T12:58:09.701    10250: 29731: 29731 I/LSPosed-Bridge  ] (IGExperiments) Using class name from Github
[ 2024-01-20T12:58:09.763    10250: 29731: 29731 E/LSPosed-Bridge  ] TgVlQGkRWEF.clsVYnC.Bz.XposedHelpers$InvocationTargetError: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /data/app/~~SJg0T_IaHTZQOUzHwOP5nw==/com.instagram.android-_4dHFA7-NyrnB4fWnTJ_kg==/base.apk
	at TgVlQGkRWEF.clsVYnC.Bz.XposedHelpers.callMethod(SourceFile:2)
	at com.chacha.igexperiments.Module.handleLoadPackage(Module.java:115)
	at TgVlQGkRWEF.clsVYnC.Bz.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at TgVlQGkRWEF.clsVYnC.Bz.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at TgVlQGkRWEF.clsVYnC.Bz.callbacks.XCallback.callAll(Unknown Source:26)
	at h0.a(Unknown Source:271)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:250)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1310)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3014)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3006)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6623)
	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /data/app/~~SJg0T_IaHTZQOUzHwOP5nw==/com.instagram.android-_4dHFA7-NyrnB4fWnTJ_kg==/base.apk
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1231)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1177)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1081)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1090)
	at java.lang.reflect.Method.invoke(Native Method)
	... 22 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Application.getSystemService(java.lang.Class)' on a null object reference
	at android.content.pm.PackageParser.parseBaseApkCommon(PackageParser.java:2400)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1892)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1215)
	... 26 more
[ 2024-01-20T12:58:16.584    10250: 31784: 31784 I/LSPosed         ] Loading xposed for com.instagram.android:mqtt/10250
[ 2024-01-20T12:58:16.634    10250: 31784: 31784 I/LSPosed-Bridge  ] Loading legacy module com.chacha.igexperiments from /data/app/~~cMT-C-vvE1l7dtPcVCDWfg==/com.chacha.igexperiments-GTgEjI_nxLDATYi42Gt-iQ==/base.apk
[ 2024-01-20T12:58:16.991    10250: 31784: 31784 I/LSPosed-Bridge  ]   Loading class com.chacha.igexperiments.Module
[ 2024-01-20T12:58:17.355    10250: 31784: 31784 I/LSPosed-Bridge  ] (IGExperiments) Using class name from Github
[ 2024-01-20T12:58:17.497    10250: 31784: 31784 E/LSPosed-Bridge  ] TgVlQGkRWEF.clsVYnC.Bz.XposedHelpers$InvocationTargetError: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /data/app/~~SJg0T_IaHTZQOUzHwOP5nw==/com.instagram.android-_4dHFA7-NyrnB4fWnTJ_kg==/base.apk
	at TgVlQGkRWEF.clsVYnC.Bz.XposedHelpers.callMethod(SourceFile:2)
	at com.chacha.igexperiments.Module.handleLoadPackage(Module.java:115)
	at TgVlQGkRWEF.clsVYnC.Bz.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at TgVlQGkRWEF.clsVYnC.Bz.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at TgVlQGkRWEF.clsVYnC.Bz.callbacks.XCallback.callAll(Unknown Source:26)
	at h0.a(Unknown Source:271)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:250)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1310)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3014)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3006)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6623)
	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /data/app/~~SJg0T_IaHTZQOUzHwOP5nw==/com.instagram.android-_4dHFA7-NyrnB4fWnTJ_kg==/base.apk
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1231)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1177)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1081)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1090)
	at java.lang.reflect.Method.invoke(Native Method)
	... 22 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Application.getSystemService(java.lang.Class)' on a null object reference
	at android.content.pm.PackageParser.parseBaseApkCommon(PackageParser.java:2400)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1892)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1215)
	... 26 more
```

here i succeed copying from log file i hope that its enough

**Comment by ReSo7200** [comment]
@xHookman Can you please check this logs?

**Comment by ReSo7200** [comment]
Hi again, @Mikicrepstudios can you please try the LSPatch method?

Install LSPatch, create a new patch using one of the supported Instagram versions APK file, then select our module.

**Comment by xHookman** [comment]
> ```
> [ 2024-01-20T12:57:27.815    10375: 24814: 24814 I/LSPosed         ] Loading xposed for com.chacha.igexperiments/10375
> [ 2024-01-20T12:57:27.851    10375: 24814: 24814 I/LSPosed-Bridge  ] Loading legacy module com.chacha.igexperiments from /data/app/~~cMT-C-vvE1l7dtPcVCDWfg==/com.chacha.igexperiments-GTgEjI_nxLDATYi42Gt-iQ==/base.apk
> [ 2024-01-20T12:57:28.015    10375: 24814: 24814 I/LSPosed-Bridge  ]   Loading class com.chacha.igexperiments.Module
> [ 2024-01-20T12:57:28.966    10375: 24814: 24814 W/LSPosed         ] New modules detected, hook preferences
> [ 2024-01-20T12:57:43.564     2000: 29730: 29730 I/LSPosed         ] Loaded manager, skipping next steps
> [ 2024-01-20T12:57:48.235        0:  4346:  4363 I/lspd            ] Background concurrent copying GC freed 344659(23MB) AllocSpace objects, 12(2608KB) LOS objects, 83% free, 4779KB/28MB, paused 78us,72us total 144.304ms
> [ 2024-01-20T12:57:54.955        0:  4346:  4372 I/LSPosedLogcat   ] !!refresh_modules!!
> [ 2024-01-20T12:57:54.962        0:  4346:  4374 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2024-01-20T11:57:54.959.log
> [ 2024-01-20T12:58:09.045    10250: 29731: 29731 I/LSPosed         ] Loading xposed for com.instagram.android/10250
> [ 2024-01-20T12:58:09.066    10250: 29731: 29731 I/LSPosed-Bridge  ] Loading legacy module com.chacha.igexperiments from /data/app/~~cMT-C-vvE1l7dtPcVCDWfg==/com.chacha.igexperiments-GTgEjI_nxLDATYi42Gt-iQ==/base.apk
> [ 2024-01-20T12:58:09.268    10250: 29731: 29731 I/LSPosed-Bridge  ]   Loading class com.chacha.igexperiments.Module
> [ 2024-01-20T12:58:09.701    10250: 29731: 29731 I/LSPosed-Bridge  ] (IGExperiments) Using class name from Github
> [ 2024-01-20T12:58:09.763    10250: 29731: 29731 E/LSPosed-Bridge  ] TgVlQGkRWEF.clsVYnC.Bz.XposedHelpers$InvocationTargetError: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /data/app/~~SJg0T_IaHTZQOUzHwOP5nw==/com.instagram.android-_4dHFA7-NyrnB4fWnTJ_kg==/base.apk
> 	at TgVlQGkRWEF.clsVYnC.Bz.XposedHelpers.callMethod(SourceFile:2)
> 	at com.chacha.igexperiments.Module.handleLoadPackage(Module.java:115)
> 	at TgVlQGkRWEF.clsVYnC.Bz.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
> 	at TgVlQGkRWEF.clsVYnC.Bz.callbacks.XC_LoadPackage.call(Unknown Source:6)
> 	at TgVlQGkRWEF.clsVYnC.Bz.callbacks.XCallback.callAll(Unknown Source:26)
> 	at h0.a(Unknown Source:271)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at J.callback(Unknown Source:250)
> 	at LSPHooker_.getClassLoader(Unknown Source:8)
> 	at android.app.LoadedApk.getResources(LoadedApk.java:1310)
> 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3014)
> 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3006)
> 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6623)
> 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7839)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> Caused by: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /data/app/~~SJg0T_IaHTZQOUzHwOP5nw==/com.instagram.android-_4dHFA7-NyrnB4fWnTJ_kg==/base.apk
> 	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1231)
> 	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1177)
> 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1081)
> 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1090)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	... 22 more
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Application.getSystemService(java.lang.Class)' on a null object reference
> 	at android.content.pm.PackageParser.parseBaseApkCommon(PackageParser.java:2400)
> 	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1892)
> 	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1215)
> 	... 26 more
> [ 2024-01-20T12:58:16.584    10250: 31784: 31784 I/LSPosed         ] Loading xposed for com.instagram.android:mqtt/10250
> [ 2024-01-20T12:58:16.634    10250: 31784: 31784 I/LSPosed-Bridge  ] Loading legacy module com.chacha.igexperiments from /data/app/~~cMT-C-vvE1l7dtPcVCDWfg==/com.chacha.igexperiments-GTgEjI_nxLDATYi42Gt-iQ==/base.apk
> [ 2024-01-20T12:58:16.991    10250: 31784: 31784 I/LSPosed-Bridge  ]   Loading class com.chacha.igexperiments.Module
> [ 2024-01-20T12:58:17.355    10250: 31784: 31784 I/LSPosed-Bridge  ] (IGExperiments) Using class name from Github
> [ 2024-01-20T12:58:17.497    10250: 31784: 31784 E/LSPosed-Bridge  ] TgVlQGkRWEF.clsVYnC.Bz.XposedHelpers$InvocationTargetError: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /data/app/~~SJg0T_IaHTZQOUzHwOP5nw==/com.instagram.android-_4dHFA7-NyrnB4fWnTJ_kg==/base.apk
> 	at TgVlQGkRWEF.clsVYnC.Bz.XposedHelpers.callMethod(SourceFile:2)
> 	at com.chacha.igexperiments.Module.handleLoadPackage(Module.java:115)
> 	at TgVlQGkRWEF.clsVYnC.Bz.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
> 	at TgVlQGkRWEF.clsVYnC.Bz.callbacks.XC_LoadPackage.call(Unknown Source:6)
> 	at TgVlQGkRWEF.clsVYnC.Bz.callbacks.XCallback.callAll(Unknown Source:26)
> 	at h0.a(Unknown Source:271)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at J.callback(Unknown Source:250)
> 	at LSPHooker_.getClassLoader(Unknown Source:8)
> 	at android.app.LoadedApk.getResources(LoadedApk.java:1310)
> 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3014)
> 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3006)
> 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6623)
> 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7839)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> Caused by: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /data/app/~~SJg0T_IaHTZQOUzHwOP5nw==/com.instagram.android-_4dHFA7-NyrnB4fWnTJ_kg==/base.apk
> 	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1231)
> 	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1177)
> 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1081)
> 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1090)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	... 22 more
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Application.getSystemService(java.lang.Class)' on a null object reference
> 	at android.content.pm.PackageParser.parseBaseApkCommon(PackageParser.java:2400)
> 	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1892)
> 	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1215)
> 	... 26 more
> ```
> 
> here i succeed copying from log file i hope that its enough

hi what rom are you using please ?

**Comment by Mikicrepstudios** [comment]
Crdroid 8.2

**Comment by ReSo7200** [comment]
> Crdroid 8.2

Have you checked the LSPatch method? and before that please try the hecker mode use these options for this version 315.0.0.0.109:
X.17I
A00
X.0gw

**Comment by Mikicrepstudios** [comment]
hecker mode worked, tysm, employee thing fixed too (also can you tell me what it does)

**Comment by ReSo7200** [comment]
> hecker mode worked, tysm, employee thing fixed too (also can you tell me what it does)

No worries!

Can you be more specific? and what employee thing?

**Comment by Mikicrepstudios** [comment]
employee options from this repo README.md, where are they and what they do

**Comment by ReSo7200** [comment]
> employee options from this repo README.md, where are they and what they do

They enable the dev options.

Our module enables them by default, however, if you wanted to update the app you have to manually enable them and disable the module.

**Comment by Mikicrepstudios** [comment]
ohk, are theres any fun experiments i can try

**Comment by ReSo7200** [comment]
> ohk, are theres any fun experiments i can try
Haha sure.

Please check this guide I tend to follow on YouTube:

[https://www.youtube.com/watch?v=B1KYTyugkwk&list=PLdJr6pm3r2bWTGUgDkph5EWLSb8p66IRn](url)

Note that some are old so you might not find them...

**Comment by Mikicrepstudios** [comment]
oh thanks will check later, you can close this issue
