### ISSUE TITLE
What can this project do?

### ISSUE THREAD

**Issue by af913337456** [xHookman/IGexperiments#37]
The readme file does not seem to indicate what this project can do, but does it enable developer options? Can't this be directly enabled in the system settings on an Android phone?

@xHookman

**Comment by ReSo7200** [comment]
> The readme file does not seem to indicate what this project can do, but does it enable developer options? Can't this be directly enabled in the system settings on an Android phone?
> 
> @xHookman

Hi!

This module enables the developer options of the Instagram app.

**Comment by jwtiyar** [comment]
> > The readme file does not seem to indicate what this project can do, but does it enable developer options? Can't this be directly enabled in the system settings on an Android phone?
> > @xHookman
> 
> Hi!
> 
> This module enables the developer options of the Instagram app.

What are they?
