### ISSUE TITLE
Revive NSFW Gboard

### ISSUE THREAD

**Issue by junedkh** [xHookman/IGexperiments#39]
Please 🙌🙌

**Comment by ReSo7200** [comment]
Hey, Can you explain more?

**Comment by junedkh** [comment]
It's an old module bro visit last [page](https://xdaforums.com/t/mod-xposed-nsfw-gboard.3522308/)

**Comment by junedkh** [comment]
@ReSo7200 actually tenor change some policy but if we can disable safe search in Google search maybe work.

**Comment by ReSo7200** [comment]
I don't know what this has to do with our module.

I will close this as not planned.

**Comment by junedkh** [comment]
It's okay brother
