### ISSUE TITLE
The home button didn't work

### ISSUE THREAD

**Issue by UwUMeoWggb** [xHookman/IGexperiments#40]
I have press the ig home button but nothing appears.I use lspatch to build the app.my phone is non root

**Comment by ReSo7200** [comment]
Hey! can you please provide us with the Instagram version you are trying to use?

**Comment by UwUMeoWggb** [comment]
Instagram 319.0.0.43.110

**Comment by ReSo7200** [comment]
> Instagram 319.0.0.43.110

Please note that this version is not supported, Please use a supported version you can find the supported versions inside the module.

If you wanted to update the app after patching a supported version please follow the guide.

I will leave this open until you try with a supported version, thanks!
