### ISSUE TITLE
Dosen't detect app non rooted pixel6a using lspatch

### ISSUE THREAD

**Issue by nono17k** [xHookman/IGexperiments#42]
iv'e been having issue instaling igexperiments the app does not detect my insta instal , no idea why liked somme screen with all the info needed .
![Screenshot_20240614-113507](https://github.com/xHookman/IGexperiments/assets/28670447/51a38e27-131b-40a2-8743-117b10332100)
![Screenshot_20240614-113521](https://github.com/xHookman/IGexperiments/assets/28670447/281c8192-cfb6-4fef-9105-51d7e2eb9d83)
![Screenshot_20240614-113532](https://github.com/xHookman/IGexperiments/assets/28670447/e8125cf6-cee2-49f4-b889-f8d72dcc75de)

![Screenshot_20240614-113524](https://github.com/xHookman/IGexperiments/assets/28670447/60536f43-8d17-489f-8fd1-ad4cc1d64be0)

**Comment by ReSo7200** [comment]
Hey! can you please share the logs?

Make sure to clear the logs first, force stop IGEXPERIMENTS and open it, export the logs and send them here.

Thanks!

**Comment by ReSo7200** [comment]
furthermore can you please tell us what IGEXPERIMENTS version you are using?

**Comment by ReSo7200** [comment]
so sorry I just noticed that you are using LSPatch (non root), when you open instagram, can you try hold clicking the Instagram's home button?

**Comment by nono17k** [comment]
sorry to have bothered i put my phone away for a few hours and now it works?
![Uploading Screenshot_20240614-133133.png…]()
