### ISSUE TITLE
Please update your Instagram app to the latest version.

### ISSUE THREAD

**Issue by kyrenlee** [xHookman/IGexperiments#44]
Please update your Instagram app to the latest version.

**Comment by ReSo7200** [comment]
Hey!

Do you mean updating the compatible Instagram versions?

**Comment by kyrenlee** [comment]
> Hey!
> 
> Do you mean updating the compatible Instagram versions?

yes, pelase！

**Comment by ReSo7200** [comment]
Please note that if you are on a rooted device or patched Instagram with (Local), you could update the Instagram app with having developer options enabled, Please follow the guide for that.

However, I will be updating both Instagram compatible versions today and the IGexperiments module during the week.

Have a great day, I will leave this open until I push the new versions :)

**Comment by ReSo7200** [comment]
Done, you can check the module now.
