### ISSUE TITLE
need help!

### ISSUE THREAD

**Issue by IamLoot** [xHookman/IGexperiments#45]
in developer setting what option do i need to select to enables SSL unpinning?

**Comment by ReSo7200** [comment]
Hey!

Thanks for using our module.


To enable SSL unpinning, follow these steps:

1. **Activate "qe ig android whitehat options**":

  - Go to the MetaConfig Categories and search for "_whitehat_".
  - Once you find the _whitehat_ option, enable it.

2. **Access Instagram's Internal Settings:**

-   Open Instagram, go to your profile, and tap on the three horizontal lines (menu).
-   Scroll down and look for the Internal settings option in the Internal section, just before the Login section.

3. **Enable SSL Unpinning:**

-   Inside Internal settings, tap on Whitehat Settings.
-   Enable both of the following options:
       _Allow user-installed certificates_
       _Do not use TLS 1.3_ (if needed)

Once you've enabled these settings, SSL unpinning should be active.

**Comment by IamLoot** [comment]
> * Go to the MetaConfig Categories and search for "_whitehat_".

there's no option like "whitehat". see attached screenshot
![IMG_20241008_152527](https://github.com/user-attachments/assets/321a79a4-08f8-472e-8041-94a8cd6e20e0)

**Comment by ReSo7200** [comment]
![Screenshot_20241008_125653_Instagram](https://github.com/user-attachments/assets/ab4406f1-a2c5-4c89-9f24-467a6e6bc79f)

Could you please confirm which Instagram version you are using?

**Comment by IamLoot** [comment]
> Could you please confirm which Instagram version you are using?

my Instagram version is 351.1.0.42.106

**Comment by ReSo7200** [comment]
Can you please try installing the latest Beta version?

**Comment by ReSo7200** [comment]
https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-352-0-0-35-100-release/

**Comment by IamLoot** [comment]
> https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-352-0-0-35-100-release/

yes it worked in beta version, thank you.

**Comment by ReSo7200** [comment]
You are more than welcome!

Please remember to star our repository if you haven't already 🙏🏼 ✨️
