### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by YashSoPro** [xHookman/IGexperiments#46]
im using Instagram 352.0.0.0.9 ig experiments 3.0 i did new patch>embed modules>igexperiment install i opened nothing happened after installing and home button after few minutes i re opened apps but this time it was crashing i tried a and s both versions

**Comment by ReSo7200** [comment]
Hey, Thanks for using our module.

So you are on a non-rooted device and patching the app with embedded option?

Could you please explain when does Instagram app crashes? or instantly?

**Comment by YashSoPro** [comment]
> Hey, Thanks for using our module.
> 
> So you are on a non-rooted device and patching the app with embedded option?
> 
> Could you please explain when does Instagram app crashes? or instantly?

it crashes when i open it it crashes instantly i removed it bur if u want i can repeat steps and give lspatch log

**Comment by ReSo7200** [comment]
I will test it today and get back to you, while I do that could you please check one of the earlier versions 2.5.1?

**Comment by ReSo7200** [comment]
Hey again, thanks for opening this ticket!

it appears there's a code bug that leads to this issue.

I will be providing a new update as soon as possible.

**Comment by YashSoPro** [comment]
> Hey again, thanks for opening this ticket!
> 
> it appears there's a code bug that leads to this issue.
> 
> I will be providing a new update as soon as possible.

i love how you respond immediately and see my problem lol will wait for your replay btw already sttarted project because its great!

**Comment by YashSoPro** [comment]
i also wanna suggest things im not promoting anything but if you know instaprefs module which is dead i think you should also add something like that so it would be cool there are tons od instagram mod which provides it but all closed source the only project i loved was this and barinsta(which was discontinued)

**Comment by ReSo7200** [comment]
> > Hey again, thanks for opening this ticket!
> > it appears there's a code bug that leads to this issue.
> > I will be providing a new update as soon as possible.
> 
> i love how you respond immediately and see my problem lol will wait for your replay btw already sttarted project because its great!

Hey! thanks for your kind words.

I am sorry for taking much long, I already found a work around, but I found another problem with the "Auto Mode" so it took a while fixing it, I will try to publish the update and the hooks in the next 3 hours.

if you are in hurry, please download this one which fixes the issue you are facing:

https://github.com/ReSo7200/IGexperiments/actions/runs/11551725797/artifacts/2111438671

**Comment by ReSo7200** [comment]
> i also wanna suggest things im not promoting anything but if you know instaprefs module which is dead i think you should also add something like that so it would be cool there are tons od instagram mod which provides it but all closed source the only project i loved was this and barinsta(which was discontinued)

I really wish I could, I am a bit noob at what I am doing, I tried to rev eng some modded insta apps, I couldn't understand them that much...

I will try when I become a little bit free in the near future, I hope.

**Comment by ReSo7200** [comment]
https://github.com/xHookman/IGexperiments/releases/tag/v3.1

here you go!

Thanks again for using our module! have a nice day :)
