### ISSUE TITLE
Always crashing

### ISSUE THREAD

**Issue by craftalpian** [xHookman/IGexperiments#49]
Hi there, thank you for the module and tutorial, but my Instagram always crashing and cannot be open. I try instagram version thats your module suggest (IGExperiments), and try other version that you suggests in the issues threads, still crashing. This proof: https://youtu.be/c5eXYX8SOTY 

ps: I'm using Emulator + Non Rooted device

**Comment by ReSo7200** [comment]
> Hi there, thank you for the module and tutorial, but my Instagram always crashing and cannot be open. I try instagram version thats your module suggest (IGExperiments), and try other version that you suggests in the issues threads, still crashing. This proof: https://youtu.be/c5eXYX8SOTY
> 
> ps: I'm using Emulator + Non Rooted device

Hello, thanks for using our module.

Please note, according to my knowledge, Instagram doesn't work on emulators, (Nox, Android studio JVM, etc...)

if you are a pen-tester, please use genymotion I remember it worked back at the day.

**Comment by craftalpian** [comment]
Thank you for the response. Do you have any suggestions for the Genymotion specifications? For example, using Android Lollipop or another version?

**Comment by ReSo7200** [comment]
> Thank you for the response. Do you have any suggestions for the Genymotion specifications? For example, using Android Lollipop or another version?

😅tbh I don't remember, I remember there was a video on youtube explaining how to intercept instagram or something...

btw, you would need root to do testing, as you might want to install the CA certificate for the proxy.
